classifiers:
  thematic:
    description: >
      Analyse et classification des posts dans des thèmes prédéfinis pour un opérateur spécifique.
    output_schema:
      - name: theme_id
        description: ID du thème identifié: 'offre', 'initiative', 'communication_interaction'
      - name: theme_name
        description: Nom du thème identifié
      - name: confidence
        description: Niveau de confiance de la classification de 0 à 1
    prompt_template: >
      prompt_template: >
        Tu es un expert en analyse de contenu pour {brand_name}.
        Le contenu à analyser est un {{content_type}}.

        {% if content_type == "comment" %}
        Ce commentaire est associé à un post dont voici les informations d’analyse :
        IMPORTANT:
        - Les commentaires peuvent être en arabe ou en français
        - Même si le commentaire est en arabe, utilise les mots-clés français pour comprendre le sens et l'intention du message
        - Considère les variations sémantiques et linguistiques entre l'arabe et le français
        - Considère le contexte du post original pour mieux comprendre le commentaire
        - Utilise l'analyse du post original pour guider ta classification
        
        
        Post original:
        {post_text}
        
        Analyse du post original:
        {post_analysis}
        {% endif %}

        Analyse ce {{content_type}} et classifie-le dans l'un des thèmes suivants :
        - **offre** : contenu concernant les produits, forfaits, promotions, services
        - **initiative** : contenu concernant les actions sociales, événements, engagements de la marque
        - **communication_interaction** : contenu lié à la relation client, annonces, concours, vœux

        IMPORTANT :
        - Le contenu peut être en arabe ou en français
        - Analyse le **contexte** et l’**intention** du message
        - Retourne uniquement l’un de ces 3 thèmes

        Contenu à analyser :
        {{text}}

        {{format_instructions}}

  intent:
    description: >
      Classification de l’intention d’un post selon son thème général.
    output_schema:
      - name: intent
        description: L'intention identifiée du post
      - name: confidence
        description: Niveau de confiance de la classification de 0 à 1
    prompt_template: >
      Tu es un expert en analyse d'intentions pour {brand_name}. 
      Le contenu à analyser est un {{content_type}}

       {% if content_type == "comment" %}
      Ce commentaire répond à un post classifié dans le thème : {{parent_post_info.theme_name}}.
      Identifie l'**INTENTION principale** de ce {{content_type}} parmi les intentions possibles pour le thème correspondant :

        {{available_intents}}

        Voici les définitions des intentions :

        **Pour OFFRE** :
         - **Question** : L'utilisateur pose une question explicite ou implicite
         - **Plainte** : L'utilisateur exprime une insatisfaction ou un mécontentement
         - **Compliment** : L'utilisateur félicite ou fait un retour positif
         - **Suggestion** : L'utilisateur propose une idée ou une amélioration
         - **Comparaison** : L'utilisateur compare Orange à un autre opérateur
         - **DemandeTechnique** : L'utilisateur demande une aide technique ou un support
         - **ExpressionInteret** : L'utilisateur manifeste de l’intérêt pour une offre ou un service
         - **PartageExperience** : L'utilisateur raconte une expérience personnelle liée à la marque
        **Pour INITIATIVE** :
        - **Félicitations** : L'utilisateur félicite ou encourage l’initiative, l’événement ou l’annonce faite par la marque
        - **Motivation** : L'utilisateur exprime un enthousiasme, une adhésion ou une motivation personnelle à participer, contribuer ou suivre l’initiative
        - **DemandeDeDetails** : L'utilisateur pose une question ou demande plus d’informations à propos d’une initiative, d’un événement ou d’une action de communication
        - **Critique** : L'utilisateur émet une remarque négative ou une désapprobation sur l’initiative, son contenu, ou la manière dont elle est présentée ou mise en œuvre
        - **PartageRessources** : L'utilisateur partage un lien, une information, une opportunité ou une ressource complémentaire en rapport avec le sujet abordé
        - **FeedbackGénéral** : L'utilisateur donne un retour global, neutre ou général, sur le sujet du post sans entrer dans un autre type spécifique


        **Pour COMMUNICATION_INTERACTION** :
        -- **Remerciement** : L'utilisateur remercie la marque ou les organisateurs pour l'information, l'événement ou l'initiative partagée
        - **RéactionAnnonce** : L'utilisateur réagit à une annonce ou une actualité de manière spontanée, sans poser de question ni donner de critique
        - **InscriptionOuParticipation** : L'utilisateur manifeste son intérêt à s'inscrire ou à participer à un événement ou une activité
        - **DemandePrécisions** : L'utilisateur demande des précisions ou des détails complémentaires sur un événement, une annonce ou une procédure
        - **HumourSarcasme** : L'utilisateur utilise un ton humoristique, ironique ou sarcastique en réponse au contenu
        - **PartageLien** : L'utilisateur partage un lien externe en lien (ou non) avec le contenu du post
        - **TagD’unAmi** : L'utilisateur identifie une ou plusieurs personnes dans le commentaire via une mention/tag
      {% else %}
      Ce post appartient au thème : {{theme_name}}.

       Identifie l'**INTENTION principale** de ce {{content_type}} parmi les intentions possibles pour le thème correspondant :

        {{available_intents}}

        Voici les définitions des intentions :

        **Pour OFFRE** :
        - **Information** : Le contenu informe sur un produit/service sans promotion explicite
        - **Promotion** : Le contenu fait la promotion d'une offre avec incitation à l'achat
        - **Feedback_Request** : Le contenu demande l'avis des clients sur un produit/service

        **Pour INITIATIVE** :
        - **CSR** : Responsabilité sociale d'entreprise, action communautaire ou environnementale
        - **Event_Announcement** : Annonce d'un événement organisé par Orange
        - **Information** : Information générale sur une initiative sans promotion

        **Pour COMMUNICATION_INTERACTION** :
        - **Alert** : Alerte, notification importante ou information urgente
        - **Holiday_Greeting** : Vœux pour les fêtes ou les occasions spéciales
        - **Contest** : Concours, jeu ou compétition
        - **Engagement** : Contenu visant à engager la communauté, question ouverte, appel à réaction
      {% endif %}

      **IMPORTANT** :
      - Le contenu peut être en arabe ou en français
      - Analyse le ton, le contexte et l'objectif du message
      - Choisis l’intention **la plus appropriée**

      Contenu à analyser :
       {{text}}

      {{format_instructions}}
  offer_category:
    description: >
      Classifie un post lié à une OFFRE dans l’une des grandes catégories d’offres disponibles.
    output_schema:
      - name: category_id
        description: ID de la catégorie d'offre identifiée
      - name: category_name
        description: Nom de la catégorie d'offre
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert des offres {brand_name} Ce {content_type} concerne une OFFRE. 
      {% if content_type == "comment" %}
        Ce commentaire est associé à un post dont voici les informations d’analyse :
        IMPORTANT:
        - Les commentaires peuvent être en arabe ou en français
        - Même si le commentaire est en arabe, utilise les mots-clés français pour comprendre le sens et l'intention du message
        - Considère les variations sémantiques et linguistiques entre l'arabe et le français
        - Considère le contexte du post original pour mieux comprendre le commentaire
        - Utilise l'analyse du post original pour guider ta classification

        Post original:
        {post_text}
        
        Analyse du post original:
        {post_analysis}
        {% endif %}

      Identifie la CATÉGORIE d'offre parmi les suivantes:

      {{categories}}

      IMPORTANT:
      - Le contenu peut être en arabe mais les mots-clés sont en français
      - Utilise les mots-clés pour identifier la bonne catégorie
      - Choisis la catégorie la plus appropriée


      Contenu à analyser:
      {{text}}

      {{format_instructions}}

  offer_subcategory:
    description: >
      Classifie une offre dans une sous-catégorie spécifique à partir de la catégorie principale.
    output_schema:
      - name: subcategory_id
        description: ID de la sous-catégorie identifiée
      - name: subcategory_name
        description: Nom de la sous-catégorie
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert des offres {brand_name}. Ce {content_type} concerne une offre de la catégorie: {{category_name}}
      {% if content_type == "comment" %}
        Ce commentaire est associé à un post dont voici les informations d’analyse :
        
        Post original:
        {post_text}
        
        Analyse du post original:
        {post_analysis}

        IMPORTANT:
        - Les commentaires peuvent être en arabe ou en français
        - Même si le commentaire est en arabe, utilise les mots-clés français pour comprendre le sens et l'intention du message
        - Considère les variations sémantiques et linguistiques entre l'arabe et le français
        - Considère le contexte du post original pour mieux comprendre le commentaire
        - Utilise l'analyse du post original pour guider ta classification

        {% endif %}
      Identifie la SOUS-CATÉGORIE spécifique parmi les suivantes pour cette catégorie:

      {{subcategories}}

      IMPORTANT:
      - Le contenu peut être en arabe mais les mots-clés sont en français
      - Utilise les mots-clés pour identifier la bonne sous-catégorie
      - Si aucune sous-catégorie ne correspond, retourne "none" comme subcategory_id

      Post à analyser:
      {{post_text}}

      {{format_instructions}}
  offer:
    description: >
      Identifie le produit ou l'offre exacte mentionnée dans un post, à partir d’une liste de produits pour une sous-catégorie donnée.
    output_schema:
      - name: product_id
        description: ID du produit/offre identifié
      - name: product_name
        description: Nom du produit/offre
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert des offres {brand_name}. Ce {content_type} concerne une offre de la sous-catégorie: {{subcategory_name}}
      
      Identifie le PRODUIT/OFFRE EXACTE parmi les suivants:
      
      {{products}}
      
      IMPORTANT:
      - Le post peut être en arabe mais les mots-clés sont en français
      - Utilise les mots-clés pour identifier le bon produit
      - Si aucun produit spécifique ne correspond, retourne "general" comme product_id
      
      Post à analyser:
      {{post_text}}
      
      {{format_instructions}}
  initiative:
    description: >
      Identifie l’initiative spécifique mentionnée dans un post, à partir d’une liste d’initiatives connues.
    output_schema:
      - name: initiative_id
        description: ID de l'initiative identifiée
      - name: initiative_name
        description: Nom de l'initiative
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert des initiatives {brand_name}. Ce post concerne une INITIATIVE. 
      Identifie l'initiative spécifique parmi les suivantes:
      
      {{initiatives}}
      
      IMPORTANT:
      - Le post peut être en arabe mais les mots-clés sont en français
      - Cherche les correspondances contextuelles et sémantiques
      - Les noms propres peuvent être transcrits différemment
      
      Post à analyser:
      {{post_text}}
      
      {{format_instructions}}
  initiative_event:
    description: >
      Identifie l’événement spécifique mentionné dans un post, parmi une liste d’événements liés à une initiative donnée.
    output_schema:
      - name: event_id
        description: ID de l'événement identifié
      - name: event_name
        description: Nom de l'événement
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert des initiatives {brand_name}. Ce {content_type} concerne l'initiative : {{initiative_name}}
      
      Identifie l'ÉVÉNEMENT spécifique parmi les suivants pour cette initiative:
      
      {{events}}
      
      IMPORTANT:
      - Le post peut être en arabe mais les mots-clés sont en français
      - Utilise les mots-clés pour identifier le bon événement
      - Si aucun événement spécifique ne correspond, retourne "general" comme event_id
      
      Post à analyser:
      {{post_text}}
      
      {{format_instructions}}
  communication_topic:
    description: >
      Identifie le type de communication ou d’interaction dans un post lié à la communication client.
    output_schema:
      - name: topic_id
        description: ID du topic de communication identifié
      - name: topic_name
        description: Nom du topic de communication
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert en communication {brand_name}. Ce post concerne la COMMUNICATION & INTERACTION. 
      Identifie le type de communication parmi les suivants:
      
      {{topics}}
      
      IMPORTANT:
      - Le post peut être en arabe mais les mots-clés sont en français
      - Considère le contexte et l'intention du message
      - Identifie le type de communication le plus approprié
      
      Post à analyser:
      {{post_text}}
      
      {{format_instructions}}
  communication_subtopic:
    description: >
      Identifie le sous-sujet spécifique d’un post de communication ou d’interaction.
    output_schema:
      - name: subtopic_id
        description: ID du sous-sujet identifié
      - name: subtopic_name
        description: Nom du sous-sujet
      - name: confidence
        description: Niveau de confiance de 0 à 1
    prompt_template: >
      Tu es un expert en communication {brand_name}. Ce post concerne le topic: {{topic_name}}
      
      Identifie le SOUS-SUJET spécifique parmi les suivants:
      
      {{subtopics}}
      
      IMPORTANT:
      - Le post peut être en arabe mais les mots-clés sont en français
      - Utilise les mots-clés pour identifier le bon sous-sujet
      - Si aucun sous-sujet spécifique ne correspond, retourne "general" comme subtopic_id
      
      Post à analyser:
      {{post_text}}
      
      {{format_instructions}}




