# ===================================================================
# Fichier de configuration des prompts pour OrangePostAnalyzer
# Chaque clé correspond à un classifieur spécifique dans le code.
# ===================================================================

# ---------------------------------
# 1. Classifieur de Thème Principal
# ---------------------------------
theme: |
  Tu es un expert en analyse de contenu pour Orange Maroc. Analyse ce post et classifie-le dans l'un des thèmes suivants:
  
  - offre: contenu concernant les produits, forfaits, offres commerciales , les cadeaux et les promotions, les services d'Orange
  - initiative: contenu concernant les initiatives de marque, programmes sociaux, événements Orange
  - communication_interaction: contenu concernant la communication client, annonces, interactions
  
  IMPORTANT:
  - Les posts peuvent être en arabe ou en français
  - Analyse le contexte et l'intention du message
  - Retourne uniquement l'un de ces thèmes
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

# --------------------------
# 2. Classifieur d'Intention
# --------------------------
intent: |
  Tu es un expert en analyse d'intentions pour Orange Maroc. 
  Ce post appartient au thème: {theme_name}
  
  Identifie l'INTENTION principale de ce post parmi les intentions possibles pour ce thème:
  
  {available_intents}
  
  Voici les définitions des intentions:
  
  Pour OFFRE:
  - Information: Le post informe sur un produit/service sans promotion explicite
  - Promotion: Le post fait la promotion d'une offre avec incitation à l'achat
  - Feedback_Request: Le post demande l'avis des clients sur un produit/service
  
  Pour INITIATIVE:
  - CSR: Responsabilité sociale d'entreprise, action communautaire ou environnementale
  - Event_Announcement: Annonce d'un événement organisé par Orange
  - Information: Information générale sur une initiative sans promotion
  
  Pour COMMUNICATION_INTERACTION:
  - Alert: Alerte, notification importante ou information urgente
  - Holiday_Greeting: Vœux pour les fêtes, occasions spéciales
  - Contest: Concours, jeu ou compétition
  - Engagement: Contenu pour engager la communauté, question ouverte
  
  IMPORTANT:
  - Le post peut être en arabe ou en français
  - Analyse le ton, le contexte et l'objectif du message
  - Choisis l'intention la plus appropriée parmi celles disponibles pour ce thème
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

# -----------------------------------
# 3. Classifieurs pour le thème OFFRE
# -----------------------------------
offre_category: |
  Tu es un expert des offres Orange Maroc. Ce post concerne une OFFRE. 
  Identifie la CATÉGORIE d'offre parmi les suivantes:
  
  {categories}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Utilise les mots-clés pour identifier la bonne catégorie
  - Choisis la catégorie la plus appropriée
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

offre_subcategory: |
  Tu es un expert des offres Orange Maroc. Ce post concerne une offre de la catégorie: {category_name}
  
  Identifie la SOUS-CATÉGORIE spécifique parmi les suivantes pour cette catégorie:
  
  {subcategories}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Utilise les mots-clés pour identifier la bonne sous-catégorie
  - Si aucune sous-catégorie ne correspond, retourne "none" comme subcategory_id
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

offre_product: |
  Tu es un expert des offres Orange Maroc. Ce post concerne une offre de la sous-catégorie: {subcategory_name}
  
  Identifie le PRODUIT/OFFRE EXACTE parmi les suivants:
  
  {products}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Utilise les mots-clés pour identifier le bon produit
  - Si aucun produit spécifique ne correspond, retourne "general" comme product_id
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

# ----------------------------------------
# 4. Classifieurs pour le thème INITIATIVE
# ----------------------------------------
initiative: |
  Tu es un expert des initiatives Orange Maroc. Ce post concerne une INITIATIVE. 
  Identifie l'initiative spécifique parmi les suivantes:
  
  {initiatives}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Cherche les correspondances contextuelles et sémantiques
  - Les noms propres peuvent être transcrits différemment
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

initiative_event: |
  Tu es un expert des initiatives Orange Maroc. Ce post concerne l'initiative: {initiative_name}
  
  Identifie l'ÉVÉNEMENT spécifique parmi les suivants pour cette initiative:
  
  {events}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Utilise les mots-clés pour identifier le bon événement
  - Si aucun événement spécifique ne correspond, retourne "general" comme event_id
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

# -------------------------------------------------------------
# 5. Classifieurs pour le thème COMMUNICATION & INTERACTION
# -------------------------------------------------------------
communication_topic: |
  Tu es un expert en communication Orange Maroc. Ce post concerne la COMMUNICATION & INTERACTION. 
  Identifie le type de communication parmi les suivants:
  
  {topics}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Considère le contexte et l'intention du message
  - Identifie le type de communication le plus approprié
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

communication_subtopic: |
  Tu es un expert en communication Orange Maroc. Ce post concerne le topic: {topic_name}
  
  Identifie le SOUS-SUJET spécifique parmi les suivants:
  
  {subtopics}
  
  IMPORTANT:
  - Le post peut être en arabe mais les mots-clés sont en français
  - Utilise les mots-clés pour identifier le bon sous-sujet
  - Si aucun sous-sujet spécifique ne correspond, retourne "general" comme subtopic_id
  
  Post à analyser:
  {post_text}
  
  {format_instructions}