# ===================================================================
# Fichier de configuration des prompts pour SearchPostAnalyzer
# Adapté pour l'analyse de posts externes
# ===================================================================

# ---------------------------------
# 1. Classifieur de Thème Principal
# ---------------------------------
theme: |
  Tu es un expert en analyse de contenu dans le secteur des télécommunications au Maroc.
  Analyse ce post provenant d'une source EXTERNE et classifie-le dans l'un des thèmes suivants:
  
  {available_themes}
  
  IMPORTANT:
  - Ce post provient d'une source externe (groupe, page, profil personnel)
  - Les posts peuvent être en arabe, français ou darija
  - Analyse le contexte, le contenu et l'intention du message
  - Retourne uniquement l'un de ces thèmes
  – Si aucun thème ne correspond de manière satisfaisante, retourne None.
  
  Post à analyser:
  {post_text}
  
  {format_instructions}

# --------------------------
# 2. Classifieur d'Intention
# --------------------------
intent: |
  Tu es un expert en analyse d'intentions dans les télécommunications au Maroc.
  Ce post provient d'une SOURCE EXTERNE et concerne la veille extérieure.
  
  Identifie l'INTENTION principale de ce post parmi les intentions suivantes pour la veille extérieure:
  
  {available_intents}
  
  Voici les définitions des intentions pour la VEILLE EXTÉRIEURE:
  
  - Information: Le post fournit des informations factuelles sur un sujet (nouveautés, annonces, actualités)
  - Feedback_Request: Le post demande l'avis du public, feedback ou retour d'expérience
  
  IMPORTANT:
  - Ce post provient d'une source externe (groupe, page, profil personnel)
  - Le post peut être en arabe, français ou darija
  - Analyse l'objectif principal: informer ou demander un retour
  - Considère le ton et le contexte du message
  - Retourne uniquement l'un de ces thèmes
  – Si aucun thème ne correspond de manière satisfaisante, retourne None.
  
  Post à analyser:
  {post_text}
  
  {format_instructions}